apiVersion: ak.dany.dev/v1
kind: Authentik
metadata:
  name: auth
spec:
  postgres:
    host: postgres-postgresql
    database: postgres
    username: postgres
    passwordSecret: postgres-postgresql
    passwordSecretKey: postgres-password
  redis:
    host: redis-master
