apiVersion: ak.dany.dev/v1
kind: Authentik
metadata:
  name: authentik
spec:
  postgres:
    host: postgres-postgresql
    database: postgres
    username: postgres
    passwordSecret: postgres-postgresql
    passwordSecretKey: postgres-password
  redis:
    host: redis-master
  ingress:
    rules:
      - host: login.example.com
        paths:
          - path: "/"
            pathType: "Prefix"
