apiVersion: ak.dany.dev/v1
kind: AuthentikUser
metadata:
  name: exampleuser
spec:
  authentikInstance: authentik
  username: user
  displayName: User
  path: users
  email: user@example.com
  password: example123
  groups:
    - supergroup
