apiVersion: ak.dany.dev/v1
kind: AuthentikGroup
metadata:
  name: supergroup
spec:
  authentikInstance: authentik
  name: supergroup
  superuser: true
---
apiVersion: ak.dany.dev/v1
kind: AuthentikGroup
metadata:
  name: subgroup
spec:
  authentikInstance: authentik
  name: subgroup
  parent: supergroup
